### PR TITLE
Add support for JamieOliver.com

### PR DESCRIPTION
**Pull request by Mark-Howe**
Stuck to conventions used in existing scrapers.

JamieOliver's 'cuisine' returned in the JSON-LD, is actually dietary information, 'Vegetarian', 'Gluten Free' etc - I've left if in the cuisine property.

### CODE REVIEW

**Comment by ssnepenthe** [comment]
Thanks!

**Comment by ssnepenthe** [comment]
Awesome!

I made a few updates including handling of notes and filtering out cuisines that include "schema.org".

I'm not sure how I feel about adding in the "nameProp" property for a single site - I have included it for now but may make some changes in the near future.

Thanks again 😄

**Comment by Mark-Howe** [comment]
I missed a fair few cases there! Had a look through the commits, hopefully the next one will be more on point now I've seen the normalisation you're going for.

Hopefully I'll be back around to do a few more in the future, feel free to let me know if I'm going off track...

**Comment by ssnepenthe** [comment]
No worries - I appreciate the help, and you're not off track at all.

I've actually been meaning to put some contributing docs together but keep putting it off - Maybe it's time for me to get on that...

**Pull request merged**
